### ISSUE TITLE
vue-disqus 5.1.0 breaks Nuxt

### ISSUE THREAD

**Issue by CAT6e** [ktquez/vue-disqus#64]
Hi

After upgrading to 5.1.0, I got this error once I run dev

> e.provide is not a function disqus

![image](https://user-images.githubusercontent.com/32860176/125759805-6ed49698-b704-4438-80b0-f6366179ab59.png)

(Maybe this causes the error?) Since there's no changelog of this version, I didn't change how I init the plugin. This is how I init the plugin.

```
import Vue from 'vue';
import VueDisqus from 'vue-disqus';

Vue.use(VueDisqus, {
  shortname: 'MYDISQUSNAME',
});
```

The only solution is to downgrade back to 4.0.1, and the error disappears.

I hope this information useful. Thank you.

Environments:
Nuxt 2.15.7
Node 14.15.3

**Comment by ktquez** [comment]
Did you solve?

**Comment by CAT6e** [comment]
@ktquez Solved by using version 4.0.1 since then. I think there's no hope of using 5.1 with Nuxt.

**Comment by ktquez** [comment]
Awesome!

@CAT6e Soon yes, when Nuxt releases support for Vue 3.
